runtime: nodejs
env: flex
env_variables:
  GB_KEY: 'AIzaSyDYtPaK8hIh_YOtmt4Gmfi4Kg1t-Qax7pc'
  access_key: 'syYq28FXq1fLEFBx'
  secret_key: 'oMHgGlk7tuhF3U9r'
  host_base: 's3.us.archive.org'
  mongoDBURI: 'mongodb://35.231.244.245:27017'
  email: 'bub.wikimedia@gmail.com'
  password: 'Bub@wikimedia'